from cartography import Cartography

cart = Cartography()
cart.add_position([1, 0], 1)
cart.add_position([1, 0], 1)
cart.add_position([1, 0], 1)
cart.add_position([1, 0], 0)
cart.add_position([0, 1], 0)
cart.add_position([0, 0], 0)
cart.add_position([-1, 0], 0)
cart.add_position([-1, 0], 0)
cart.add_position([-1, 0], 0)
cart.add_position([-1, 0], 0)
cart.add_position([0, -1], 0)
cart.add_position([-1, 0], 0)
cart.add_position([-1, 0], 0)
cart.add_position([-1, 0], 0)
cart.add_position([-1, 0], 0)
cart.add_position([0, -1], 0)
cart.add_position([0, 0], 0)
cart.add_position([1, 0], 0)
cart.add_position([1, 0], 0)
cart.add_position([1, 0], 0)
cart.add_position([1, 0], 0)
cart.add_position([0, 0], 0)

#should be ignored as a complete circuit turn has been done
cart.add_position([1, 0], 0)
cart.add_position([1, 0], 0)
cart.add_position([1, 0], 0)
cart.add_position([1, 0], 0)

cart.draw_circuit()
