#! /usr/bin/python3

from simulator import Simulator
from colors import White, DarkShadow, Yellow
from layers import Background, DrawLines, Perspective, Crop, Symmetric
from noise import Shadows, Filter, NoiseLines, Enhance


import argparse


white = White()
yellow = Yellow()
shadow = DarkShadow()

def generate(n_examples, n_backgrounds=50, path='output'):

    simulator = Simulator()

    # background (top view)
    #  -> nb background
    #  -> nb rotations
    #  -> nb crop
    #  -> nb resize
    simulator.add(Background(n_backgrounds=n_backgrounds,
                             n_rot=5,
                             n_crop=5,
                             n_res=5,
                             path='../ground_pics',
                             input_size=(250, 200)))

    """ LAYERS """

    # draw lines
    #  -> thickness
    #  -> color
    #  -> radius
    simulator.add(DrawLines(input_size=(250, 200),
                            color_range=white, 
                            middle_line=(20, 50, "dashed", yellow),
                            thickness_range=[5, 6, 7, 8, 9],
                            target_ratio=0,
                            straight_line_rate=0))

    # add perspective
    simulator.add(Perspective())

    # remove empty space generated by perspective
    simulator.add(Crop())

    # duplicate each image and mirror
    simulator.add(Symmetric())

    """ NOISES """

    # blur + gauss_blur + smooth + smooth_more + rank_filter <= 1
    simulator.add(Filter(blur=0.1, smooth=0.1, smooth_more=0.1, rank_filter=0.1))

    # brightness + contrast + sharpness <= 1
    simulator.add(Enhance(brightness=0.8, contrast=0.1, sharpness=0.1))



    """ GENERATE """
    simulator.generate(n_examples=n_examples, path=path)

if __name__ == '__main__':

    """
    /!\ Note that generator will generate 2 times the number of
        images asked for because of the symmetric layer so if you write 200 it
        will generate 400.
    """
    parser = argparse.ArgumentParser(description='Road generator')
    parser.add_argument('-n', help='number of images to generate', dest='n_imgs', type=int, default=100)
    parser.add_argument('-p', help='output path', dest='path', type=str, default='output')
    parser.add_argument('--test', help='enable test mode', dest='test', action='store_true')
    parser.set_defaults(test=False)

    args = parser.parse_args()
    generate(args.n_imgs, n_backgrounds=1 if args.test else 50, path=args.path)
