#! /usr/bin/python3

from simulator import Simulator
from colors import White, DarkShadow, Yellow
from layers import Background, DrawLines, Perspective, Crop, Symmetric
from noise import Shadows, Filter, NoiseLines, Enhance


simulator = Simulator()
white = White()
yellow = Yellow()
shadow = DarkShadow()

""" LAYERS """

# background (top view)
#  -> nb background
#  -> nb rotations
#  -> nb crop
#  -> nb resize
simulator.add(Background(n_backgrounds=50, n_rot=5, n_crop=5, n_res=5, path='../ground_pics', input_size=(250, 200)))

# draw lines
#  -> thickness
#  -> color
#  -> radius
simulator.add(DrawLines(input_size=(250, 200),
                        color_range=white, 
                        middle_line=(0, 0, "dashed", yellow),
                        radius_range=list(range(200, 500)) + list(range(4700, 5300)),
                        thickness_range=[4, 5, 6, 7, 8]))

# add perspective
simulator.add(Perspective())

# remove empty space generated by perspective
simulator.add(Crop())

simulator.add(Symmetric())


""" NOISES """

# add shadow
simulator.add(Shadows(colors=shadow))

# blur + gauss_blur + smooth + smooth_more + rank_filter <= 1
simulator.add(Filter(blur=0.2, gauss_blur=0.2, smooth=0.2, smooth_more=0.2, rank_filter=0.2))

# brightness + contrast + sharpness <= 1
simulator.add(Enhance(brightness=0.4, contrast=0.3, sharpness=0.3))


simulator.generate(n_examples=1000, path='dataset_simulator')
